add airgap build

diff --git a/.github/workflows/build-release.yaml b/.github/workflows/build-release.yaml
--- a/.github/workflows/build-release.yaml
+++ b/.github/workflows/build-release.yaml
@@ -9,7 +9,7 @@ on:
 
 env:
   chart_name: replibot
-
+  app_id: 2S2KBYYp3fKkP42pb3eJYIYJNYv
 
 jobs:
   build:
@@ -70,7 +70,7 @@ jobs:
         id: get-channel-release-sequence
         run: |
           curl --request GET \
-            --url https://api.replicated.com/vendor/v3/app/${{ secrets.REPLICATED_APP_ID }}/channel/2pusnQ3dbpDq0SEVEE8LCeUCCwC/releases \
+            --url https://api.replicated.com/vendor/v3/app/${{ env.app_id }}/channel/2pusnQ3dbpDq0SEVEE8LCeUCCwC/releases \
             --header 'Authorization: ${{ secrets.REPLICATED_API_TOKEN }}' \
             --header 'accept: application/json' | jq -r '.releases[0].channelSequence' > channel-release-sequence.txt
           cat channel-release-sequence.txt
@@ -79,6 +79,40 @@ jobs:
       - name: build airgap
         run: |
           curl --request POST \
-            --url https://api.replicated.com/vendor/v3/app/${{ secrets.REPLICATED_APP_ID }}/channel/2pusnQ3dbpDq0SEVEE8LCeUCCwC/release/${{ steps.get-channel-release-sequence.outputs.channel-release-sequence }}/airgap/build \
+            --url https://api.replicated.com/vendor/v3/app/${{ env.app_id }}/channel/2pusnQ3dbpDq0SEVEE8LCeUCCwC/release/${{ steps.get-channel-release-sequence.outputs.channel-release-sequence }}/airgap/build \
             --header 'Authorization: ${{ secrets.REPLICATED_API_TOKEN }}' \
             --header 'accept: application/json'
+            - name: Sleep for 60 seconds
+            run: sleep 60s
+            shell: bash
+          
+      - name: check airgap build success
+        run: |
+          max_retries=5
+          attempt=0
+
+          while true; do
+            status=$(curl --silent --request GET \
+              --url https://api.replicated.com/vendor/v3/app/${{ env.app_id }}/channel/2pusnQ3dbpDq0SEVEE8LCeUCCwC/releases \
+              --header "Authorization: ${{ secrets.REPLICATED_API_TOKEN }}" \
+              --header "accept: application/json" | jq -r '.releases[0].airgapBuildStatus')
+
+            echo "Current airgapBuildStatus: $status"
+
+            if [ "$status" == "built" ]; then
+              echo "Airgap build is complete!"
+              break
+            elif [ "$status" == "failed" ]; then
+              echo "Airgap build has failed. Exiting with error."
+              exit 1
+            fi
+
+            attempt=$((attempt + 1))
+            if [ "$attempt" -ge "$max_retries" ]; then
+              echo "Maximum retries reached. Exiting with error."
+              exit 1
+            fi
+
+            echo "Airgap build not yet complete. Attempt $attempt/$max_retries. Waiting for 30 seconds..."
+            sleep 30
+          done
